package storm.starter.bolt;

import backtype.storm.tuple.Tuple;
import com.yammer.metrics.core.*;
import org.apache.log4j.Logger;
import storm.starter.Application;
import storm.starter.metrics.MetricsManager;
import storm.starter.tools.Rankings;
import storm.starter.util.Action1;

import java.util.concurrent.TimeUnit;

/**
 * This bolt merges incoming {@link Rankings}.
 * <p/>
 * It can be used to merge intermediate rankings generated by {@link IntermediateRankingsBolt} into a final,
 * consolidated ranking. To do so, configure this bolt with a globalGrouping on {@link IntermediateRankingsBolt}.
 */
public final class TotalRankingsBolt extends AbstractRankerBolt {

    private String meterName;
    private String timerName;

    private static final long serialVersionUID = -8447525895532302198L;
    private static final Logger LOG = Logger.getLogger(TotalRankingsBolt.class);

    public TotalRankingsBolt() {
        super();
        registerMetrics();
    }

    public TotalRankingsBolt(int topN) {
        super(topN);
        registerMetrics();
    }

    public TotalRankingsBolt(int topN, int emitFrequencyInSeconds) {
        super(topN, emitFrequencyInSeconds);
        registerMetrics();
    }

    private void registerMetrics(){
        MetricName metricName = new MetricName(TotalRankingsBolt.class, "requests");
        Meter requests = Application.getMetrics().newMeter(metricName, "execute", TimeUnit.SECONDS);
        meterName = metricName.toString();
        MetricsManager.register(meterName, requests);

        MetricName timerMetric = new MetricName(TotalRankingsBolt.class, "updateTotalRankings");
        Timer timer = Application.getMetrics().newTimer(timerMetric, TimeUnit.SECONDS, TimeUnit.SECONDS);
        timerName = timerMetric.toString();
        MetricsManager.register(timerName, timer);
    }

    @Override
    void updateRankingsWithTuple(final Tuple tuple) {
        MetricsManager.interactWith(timerName, new Action1<Timer>() {
            @Override
            public void invoke(Timer arg) {
                TimerContext time = arg.time();
                try {
                    Rankings rankingsToBeMerged = (Rankings) tuple.getValue(0);
                    Rankings rankings = getRankings();
                    rankings.updateWith(rankingsToBeMerged);
                    rankings.pruneZeroCounts();
                } finally {
                    time.stop();
                }
            }
        });

    }

    @Override
    void onExecute() {
        MetricsManager.interactWith(meterName, new Action1<Meter>() {
            @Override
            public void invoke(Meter arg) {
                arg.mark();
            }
        });
    }

    @Override
    Logger getLogger() {
        return LOG;
    }

}
